### PR TITLE
Added alexruperez.com to blogs.json

### PR DESCRIPTION
**Pull request by alexruperez**

### CODE REVIEW

**Comment by daveverwer** [comment]
Thanks Alex! 

Is this a feed of things you star on GitHub or is there writing there also? When I look at the feed it looks like maybe just your GitHub feed?

**Comment by alexruperez** [comment]
Thank you @daveverwer!

Yes, I have been personally selecting and promoting GitHub repos that I consider outstanding/interesting for years, I think it can be interesting. But if it is not the approach you are looking for, no problem, you can close the pull request. 🙂

**Comment by daveverwer** [comment]
When you put it like that, I agree it should be included. It's just that the feed also included things like tags being created in your repos and so I thought it might be a little less structured than that. I'll merge it now. Thanks.

**Comment by alexruperez** [comment]
@daveverwer opps, that tag is a bug in my code! Hehe. Thanks for the merge and the feedback, I'll fix it. 👍

**Pull request merged**
