### PR TITLE
Add The Always Right Institute

### PR DESCRIPTION
**Pull request by helje5**
Swift and more.

### CODE REVIEW

**Comment by daveverwer** [comment]
Just a quick one before I merge this, is this a company blog or an individual one? Looks like maybe it's a company?

**Comment by helje5** [comment]
This is definitely more of a personal one, even though i’m self employed and borders sometimes cross.

**Comment by helje5** [comment]
(the ari is non an actual institute but fake, in case that isn’t obvious 😬)

**Comment by daveverwer** [comment]
Sounds good! Figured as much but wanted to check.

**Pull request merged**
