### PR TITLE
Adds Academie Ryfacto | Advanced iOS Craft

### PR DESCRIPTION
**Pull request by nverinaud**
I started writing about iOS development, so here is my contribution !

Thanks ! 🎉

### CODE REVIEW

**Comment by daveverwer** [comment]
I'm at a bit of a disadvantage here as I don't speak French, but I can't see the blog content on the page you posted. How do I navigate to the blog from the home page? I've tried a few Google Translate queries but I'm still struggling 😀

Thanks!

**Comment by nverinaud** [comment]
Since I have only posted one article you will not find a list of articles. 

I plan to release the "Advanced iOS Craft" page next week, you will find it here : https://academie.ryfacto.fr/advanced-ios-craft

I will keep you informed when it's live !

**Comment by daveverwer** [comment]
No need to do that, I'm assuming the home page *is* the list of posts then? That's great. Merged 👍

**Comment by nverinaud** [comment]
Yep it's ok ! I'll probably do another PR to update the page pointing to the list of posts.

Thank you !

**Pull request merged**
