### PR TITLE
Update blogs.json

### PR DESCRIPTION
**Pull request by superpeteblaze**
Add Pete Smith on Medium - iOS Development blog

### CODE REVIEW

**Review by daveverwer — APPROVED** [review]
Thanks, Pete!

**Comment by superpeteblaze** [comment]
Hi @daveverwer. I was just checking in with the Dev Directory, but don't see my added link. Wondering if maybe something went wrong with a build/deployment?

**Comment by daveverwer** [comment]
Hmm. I just checked the build logs on Netlify and there are no errors, but you're right that your blog isn't there. Looking into it.

**Comment by daveverwer** [comment]
Manual re-deploy seemed to work. Thanks for noticing! I'll keep an eye on whether this is a problem going forward.

Thanks Pete

**Comment by superpeteblaze** [comment]
Awesome! Thanks Dave 🙌🏽

**Pull request merged**
