### PR TITLE
Add marcelvoss.com to blogs.json

### PR DESCRIPTION
**Pull request by marcelvoss**
This adds my blog on iOS/macOS development to the `Development Blogs` category. 😄

### CODE REVIEW

**Review by daveverwer — APPROVED** [review]
Thank you!

**Comment by daveverwer** [comment]
Looks like we have an extra comma at the end that it's complaining about. Sorry!

**Comment by marcelvoss** [comment]
All good, on it already!

**Comment by daveverwer** [comment]
Thanks!

**Pull request merged**
