### PR TITLE
Add Tenniskeeper Blog

### PR DESCRIPTION
**Pull request by tenniskeeper**

### CODE REVIEW

**Comment by daveverwer** [comment]
From a quick look at this it looks to be more about _using_ Tennis apps rather than about _developing_ Tennis apps. If it's about developing them (I didn't read everything there) then it qualifies, but I'm not sure this is a great fit from what I saw?

**Comment by tenniskeeper** [comment]
Hi Dave, it is about the TennisKeeper app that I created. Here is the App
Store link to the actual app and also the web page.

https://itunes.apple.com/app/tenniskeeper/id1097388824

http://www.tenniskeeperapp.com/

I saw Slopes ( a similar app for Snowboarding ) by Curtis Herbert is also
listed so I thought it belongs to the same marketing space. Similar to
Curtis, I am also experimenting to be an Indie developer and trying to see
if it may work out. His blog is something that I follow too.

As to if it is appropriate, I will let you decide. I will be happy to add
more content regarding to developing them in the future. I think there is
some now in the area of HealthKit, Complications, iCloud and iMessage.

Thanks.


TennisKeeper
https://www.facebook.com/tenniskeeper/

**Comment by daveverwer** [comment]
Thanks for getting back to me! I think the biggest difference between the Slopes blog and this one is that Curtis is talking about what works and what doesn't in terms of marketing on that app rather than just talking about the features that have been added etc... I'm not sure if the difference is clear!

I think what you're doing is great, and I'd love to get the blog included if you include some content that isn't just about the features of the app and more about what's working/what isn't or any content which would appeal to developers. This could be a different blog, if you want to keep the two things separate?

**Comment by tenniskeeper** [comment]
Sure, will these ideas work?

1. My experience with adding a new App Store Subscription release recently.
Sadly it took 4 times to pass the App Store review process.
2. My experience with App Store review comments. As a small developer, I
think what I saw is quite different from what others have written already.
3. Right now I am analyzing the data collected from Device Motion (Core
Motion), the raw data could turn out to be quite interesting for a
development article.

I can just add it to the same blog and use Medium heading to categorize it
I think.


TennisKeeper
https://www.facebook.com/tenniskeeper/

**Comment by daveverwer** [comment]
Of course! Anything in that kind of direction would make this 100% relevant here.

**Comment by daveverwer** [comment]
I should have also said, I've closed this for now but please feel free to either submit a new PR or re-open this one when the blog is a little more relevant! Thanks!

**Comment by tenniskeeper** [comment]
Sure will do. Thanks you.

**Pull request closed without merging**
