### PR TITLE
 Add NSProgrammer to iOS Dev Blogs

### PR DESCRIPTION
**Pull request by NSProgrammer**
Add NSProgrammer.com to the list of iOS Development Blogs

### CODE REVIEW

**Comment by daveverwer** [comment]
Just double checking, but the latest post to this blog is from 2013? If so, please add it to the Inactive section.

**Comment by NSProgrammer** [comment]
You're right!  Moved :)

**Comment by daveverwer** [comment]
I think the podcast is inactive now too? I'm not sure I want to start an inactive podcast section really. Is there value in cataloguing more blogs/podcasts that are years out of date? I'm not sure there is really.

**Comment by NSProgrammer** [comment]
Ah, sure, makes sense.  The podcast was topical so could be picked up like a reference but I see the value of keeping things curated to current stuff.  I’ll adjust.

**Pull request merged**
