### PR TITLE
Update blogs.json to include invonto company 

### PR DESCRIPTION
**Pull request by gonzalezi2**

### CODE REVIEW

**Comment by daveverwer** [comment]
Hey! Thanks for this. I can't quite find the blog on your home page. Is there a URL I can use to get to the index of posts? I'd like to read them before adding it.

Thanks!

**Comment by gonzalezi2** [comment]
Ah sorry should the site_url be the blog? I may have misunderstood that. Anyway, here's the link https://www.invonto.com/insights/

**Comment by daveverwer** [comment]
I mean it doesn't necessarily have to be, I just couldn't find the blog on your site. I did find a couple of posts in one of the dropdowns, but I couldn't find an index.

**Comment by gonzalezi2** [comment]
Yeah the owner renamed it to insights instead of blog/posts and I can't really change it. Is there anything else I need to do?

**Comment by daveverwer** [comment]
Nope, I'm merging it now.

**Comment by daveverwer** [comment]
Thanks! Merged.

**Comment by gonzalezi2** [comment]
Thank you!

**Pull request merged**
