### PR TITLE
Added the Savvy Apps blog to the directory

### PR DESCRIPTION
**Pull request by kenyarmosh**

### CODE REVIEW

**Comment by daveverwer** [comment]
Before I merge this, the blog seems to cover quite a number of topics. I noticed that they were categorised and the iOS category looks like a great fit for inclusion here. I couldn't find an RSS feed for that category though, is there one?

**Comment by kenyarmosh** [comment]
@daveverwer Thanks for the quick response. I think your audience would appreciate getting some analysis perspective that we don't tag exclusively in the iOS category. You previously have linked to some of our articles in non-iOS categories in the newsletter [like this one.](http://savvyapps.com/blog/how-much-does-app-cost-massive-review-pricing-budget-considerations
) All of our articles are app-focused but like some of the other company blogs listed, we try to touch on some broader considerations. Hopefully you'll consider adding the main feed. Let me know. :)

**Comment by daveverwer** [comment]
I think some of the posts outside the iOS category certainly qualify as relevant but there's quite a lot of non iOS content.

I will add it if there's no categorised feeds as I'd like to include all content, but I'd also ask if there is any kind of feed available that might narrow down the content a bit?

**Comment by kenyarmosh** [comment]
@daveverwer As of now, we do not have any category feeds. We certainly can look into that in the future. Thanks again for the consideration!

**Comment by daveverwer** [comment]
I think it'd be a great idea and you could include various feeds in various different sections with this (for example, we just added a Marketing section which wold suit some of the posts on your blog.

However, until that's done I'll add it here for now. Thanks for submitting it

**Pull request merged**
