### PR TITLE
Add "How to evolve a legacy iOS Application written in Swift" 

### PR DESCRIPTION
**Pull request by tiagomartinho**
by Tiago Martinho & Lewis Black

### CODE REVIEW

**Comment by daveverwer** [comment]
Thanks for this. Generally this section is for YouTube channels rather than playlists. Is the plan for this channel to be not related to iOS development after this playlist is complete? If so, I think the playlist is the right choice for the site, if not I think the channel might be better.

Thanks!
Dave

**Comment by daveverwer** [comment]
Also, I just noticed that the feed_url isn't to an RSS feed. No matter whether the link is eventually to the channel or the playlist, that will need correcting to be a valid RSS/Atom feed.

**Comment by tiagomartinho** [comment]
Thanks @daveverwer ! 

I updated the RSS feed to be the correct one.

Right now we are using my personal youtube channel, in the future we might create a dedicated one.

Thanks again for the awesome work.

**Comment by daveverwer** [comment]
I just changed the displayed name so it would fit on the site but thanks for the RSS change! Merged.

**Pull request merged**
