### PR TITLE
Update blogs.json

### PR DESCRIPTION
**Pull request by mycodetips**
Please check and merge , if there is any changes required please add comment

### CODE REVIEW

**Review by daveverwer — COMMENTED** [review]
Hi Ranjan

Is the URL correct? The server times out for me.

Thanks!

**Comment by mycodetips** [comment]
Yes, the url is correct .

https://mycodetips.com/


Thanks
MyCodeTips Team
mail : ***@***.*** | ***@***.***
skype : mycodetips

Facebook <https://www.facebook.com/mycodetips> | Twitter
<https://www.twitter.com/mycodetips> | Instagram
<https://www.instagram.com/mycodetips>

**Comment by daveverwer** [comment]
OK, thanks.

It's still not responding for me yet, but I'll try it again later.

**Comment by mycodetips** [comment]
Sounds good, thanks!

Thanks
MyCodeTips Team
mail : ***@***.*** | ***@***.***
skype : mycodetips

Facebook <https://www.facebook.com/mycodetips> | Twitter
<https://www.twitter.com/mycodetips> | Instagram
<https://www.instagram.com/mycodetips>

**Comment by daveverwer** [comment]
I'm really sorry, but the site still isn't loading for me. Can you double check it is available for you, please?

**Comment by mycodetips** [comment]
It's loading and works well. but no-worry keep me updated once done.

Thanks
MyCodeTips Team
mail : ***@***.*** | ***@***.***
skype : mycodetips

Facebook <https://www.facebook.com/mycodetips> | Twitter
<https://www.twitter.com/mycodetips> | Instagram
<https://www.instagram.com/mycodetips>

**Pull request closed without merging**
