### PR TITLE
Added Mastodon URL.

### PR DESCRIPTION
**Pull request by shiftingsand**

### CODE REVIEW

**Comment by daveverwer** [comment]
Thanks, Chris! All it needs is one extra comma 👍

**Comment by shiftingsand** [comment]
I added it and pushed it. Is that all I need to do? I'm rusty with pull requests!

**Comment by daveverwer** [comment]
That's it!, Thanks Chris 👍

**Comment by shiftingsand** [comment]
Thanks Dave!!

**Pull request merged**
