### PR TITLE
Add roger.ml blog site

### PR DESCRIPTION
**Pull request by rogerluan**
Hi there! 👋

Just adding my personal blog site with all the metadata following the site's instructions I found here: https://iosdevdirectory.com/contributing/

I tried adding the new element of the array following alphabetical order, idk if I got it right, though haha. This might be a step of the CI (to sort the array of blogs in the JSON so the JSON is organized), but I wasn't sure 😅 

Cheers!

### CODE REVIEW

**Review by daveverwer — APPROVED** [review]

**Comment by daveverwer** [comment]
Thanks Roger!

Don't worry about the alphabetical order, I run a re-sort every now and then to clean things up. I'm not strict on the sorting and the site sorts correctly regardless of the data file.

**Comment by rogerluan** [comment]
Awesome! Thank you! 🤗

**Comment by rogerluan** [comment]
@daveverwer , just wondering, is the https://iosfeeds.com homepage supposed to be updated with past entries of my blog, or just new ones? I see my blog in https://iosfeeds.com/feeds but the articles I published prior to this PR aren't showing up in the homepage, I wonder if it's the expected behavior :) 

Thanks in advance! 🙏

**Comment by daveverwer** [comment]
I'm afraid that's not my project and so I am not sure. It uses the data from this site, but it's @nemecek-filip who runs that!

**Comment by rogerluan** [comment]
Ooooh, my bad! I thought it was yours too 😂 

Thanks for clarifying and for tagging Filip 🤗

**Comment by nemecek-filip** [comment]
Hello @rogerluan, all past entires are indexed (for search) but only those published after the initial import are visible on the homepage. This is because RSS feeds often don't have correct published dates and adding new feeds often caused to display all blog posts at once.

**Comment by rogerluan** [comment]
Hi @nemecek-filip 👋 got it! Thanks for explaining, and for the prompt response! 😊

**Pull request merged**
