### PR TITLE
Speed up link validation a bit to make this tool more effective.

### PR DESCRIPTION
**Pull request by jeroenleenarts**
Needs to be tested on Github Actions to check if this is now viable to run on each commit.

With time I get this result:

`bundle exec rake validate:ping  7,40s user 11,03s system 38% cpu 48,337 total`

Much quicker... only compromise is a 10 second timeout instead of default 30.

This is the output on my run.

```
404 for https://machinelearning.apple.com/feed.xml
404 for https://arielelkin.github.io/feed
404 for https://medium.com/feed/@chris.mash
404 for https://medium.com/@chris.mash
404 for https://colindrake.me/post/
404 for https://colindrake.me/post/index.xml
404 for https://appmakers.dev/category/ios/
404 for https://appmakers.dev/category/ios/feed/
Socket Error for https://www.davenott.co.uk/
Socket Error for https://www.davenott.co.uk/feed/
404 for http://danielemargutti.com/atom.xml
SSL Error for https://microblog.dave256apps.com/feed.xml
SSL Error for https://microblog.dave256apps.com/
Socket Error for http://ausios.com/feed/
Socket Error for http://ausios.com
403 for http://ennioma.com/
403 for http://ennioma.com/rss
404 for https://rss.app/feeds/tPWkcHnpdDcjdOtB.xml
404 for http://etolstoy.com/feed.xml
SSL Error for https://getonthestore.com/feed/
SSL Error for https://getonthestore.com/
Timeout for https://blog.alltheflow.com
Timeout for https://blog.alltheflow.com/rss/
429 for https://www.ioscreator.com/tutorials?format=RSS
404 for http://jamesdempsey.net/feed/
SSL Error for http://jamesonquave.com/blog/
SSL Error for http://jamesonquave.com/blog/feed/
Timeout for http://bitsplitting.org
Timeout for http://bitsplitting.org/feed/
Errno::ECONNREFUSED Failed to open TCP connection to kayathomas.info:443 (Connection refused - connect(2) for "kayathomas.info" port 443) for https://kayathomas.info/feed/
Errno::ECONNREFUSED Failed to open TCP connection to kayathomas.info:443 (Connection refused - connect(2) for "kayathomas.info" port 443) for https://kayathomas.info
404 for https://www.latenightswift.com/feed.xml
404 for https://jsorge.net/rss/
404 for https://paraside.in/tags/swift/
404 for https://paraside.in/feed.rss
404 for https://mar.codes/feed
404 for http://www.marisibrothers.com/feeds/posts/default
404 for https://marcosantadev.com/rss
404 for https://marcosantadev.com/tag/ios/
Socket Error for https://glenngonda.com/blog
404 for https://medium.com/feed/@mobilefactory
404 for http://moraleda.info/atom.xml
404 for https://medium.com/@mobilefactory/
404 for https://www.morningswiftui.com/blog?format=RSS
404 for https://netsplit.com/feed/
404 for https://www.oliverbinns.co.uk/index.php/blog
404 for https://152percent.com/blog
404 for https://152percent.com/blog?format=RSS
404 for https://onmyway133.github.io/atom.xml
404 for https://www.pointfree.co/blog/feed/atom.xml
404 for https://www.pointfree.co/blog
Timeout for http://indiestack.com
Timeout for http://indiestack.com/feed/
Errno::ENETUNREACH Failed to open TCP connection to blog.mengto.com:80 (Network is unreachable - connect(2) for "blog.mengto.com" port 80) for http://blog.mengto.com
Errno::ENETUNREACH Failed to open TCP connection to blog.mengto.com:80 (Network is unreachable - connect(2) for "blog.mengto.com" port 80) for http://blog.mengto.com/feed/
Net::ReadTimeout Net::ReadTimeout for https://andrewking.ca/category/ios-development/feed/rss
Net::ReadTimeout Net::ReadTimeout for https://andrewking.ca/category/ios-development
Socket Error for http://www.russbishop.net
400 for https://pewpewthespells.com/
Timeout for https://crsantos.info/rss.xml
Timeout for https://crsantos.info
404 for http://sealedabstract.com/feed/
404 for https://ruiper.es/rss/
Errno::ENETUNREACH Failed to open TCP connection to www.natashatherobot.com:443 (Network is unreachable - connect(2) for "www.natashatherobot.com" port 443) for https://www.natashatherobot.com
Errno::ENETUNREACH Failed to open TCP connection to www.natashatherobot.com:443 (Network is unreachable - connect(2) for "www.natashatherobot.com" port 443) for https://www.natashatherobot.com/feed/
Socket Error for https://swiftdevjournal.com/
404 for https://swifting.io/feed/
429 for https://swiftramen.com/home?format=rss
SSL Error for https://swiftier.co
404 for https://tanaschita.com/feed.rss
SSL Error for https://swiftier.co/feed
404 for https://www.tanin.dev/tags/ios
404 for https://tanin.dev/tags/ios/index.xml
404 for https://whackylabs.com/feed.xml
Timeout for https://mobileinvader.com
Timeout for https://mobileinvader.com/feed/
429 for https://yonaskolb.com/
429 for http://www.elischiff.com/
404 for https://www.scotthurff.com/rss/
404 for https://appmanager.io/blog
404 for https://blog.adapty.io/feed
404 for http://bohemiancoders.tumblr.com/
404 for http://bohemiancoders.tumblr.com/rss
404 for https://badootech.badoo.com/feed/tagged/ios
429 for https://heyimakeapps.com/blog/
Timeout for https://parveenkaler.com/blog
Timeout for https://parveenkaler.com/feed
Net::ReadTimeout Net::ReadTimeout for https://icalvin.dev/
Net::ReadTimeout Net::ReadTimeout for https://icalvin.dev/posts/json
SSL Error for https://blog.quicktype.io/
404 for https://realm.io/feed.xml
SSL Error for https://blog.quicktype.io/rss/
HTTParty::RedirectionTooDeep HTTP redirects too deep for https://peripheryapp.com/blog/
HTTParty::RedirectionTooDeep HTTP redirects too deep for https://www.peripheryapp.com/blog/feed.xml
500 for https://blog.lemi.travel/category/technology/ios/feed/
404 for https://sudo.isl.co/atom.xml
404 for https://sudo.isl.co/
Socket Error for https://cmdswift.com/
404 for https://blog.zeplin.io/feed
Socket Error for http://sharedinstance.com
Timeout for http://stuartkhall.com/
SSL Error for https://waitingforreview.com/
404 for https://medium.com/feed/whoknows-swift
404 for https://medium.com/whoknows-swift
405 for https://sungdoo.dev
404 for http://www.alexruperez.com/entries
```

### CODE REVIEW

**Comment by nemecek-filip** [comment]
If I may chime in... this sort of validation is a bit tricky. I used to have this on iOSFeeds.com but disabled it, because it had a lot of false positives and I would end up excluding a few blogs due to temporary issues.

**Comment by jeroenleenarts** [comment]
Agreed, this check is purely to trigger a follow-up. The number of 40x codes is interesting.

**Comment by daveverwer** [comment]
Yes, I had forgotten this tool was there, actually! It's been a long time since I used it.

My method for finding dead feeds is to manually check their history with my feed aggregator, Inoreader. For any feed that's showing a redirect or any kind of error, I go and click into the history and get something like this:

Screenshot 2021-09-20 at 12 56 49@2x

If it's been 404ing for a while, I go through a set of steps like checking if the domain is still active, if there's an RSS meta tag and if it's pointing at a new file (I wish people would set up redirects! 🙏) and various other things to see if I can find the new feed and update the metadata accordingly.

Of course, this takes a very long time to do for 800+ feeds. Subsequently, I put off doing it 😂
 
It's definitely due for a check though. I'll bump it up in my priorities.

**Comment by daveverwer** [comment]
It's currently showing more than 90 as completely dead, so definitely time for me to do a thorough check:

Screenshot 2021-09-20 at 13 05 47@2x
.

**Comment by jeroenleenarts** [comment]
Feedly reports 46 broken sources.

**Comment by daveverwer** [comment]
> Feedly reports 46 broken sources.

Across all of the OPML files, or a subset?

**Comment by jeroenleenarts** [comment]
All of the OPML.

**Comment by daveverwer** [comment]
That's very strange. Inoreader doesn't usually give false positives for errors. 

I'll look into doing the full check as soon as I have time.

I think I'll merge this PR as even though this tool is not ideal, this *is* an improvement to it. 👍 Thanks again for putting it together

**Pull request merged**
