### PR TITLE
Add Audio Dev News & iOS Developer Interviews

### PR DESCRIPTION
**Pull request by analogcode**
Weekly iOS Audio App Developer Interviews & Audio Developer News
Curated by the AudioKit open-source project

### CODE REVIEW

**Comment by analogcode** [comment]
Not sure where the AudioKit blog should go? It's not a company. And, the majority of the iOS Developers we've interviewed don't use AudioKit in their apps. (There's something in there for everyone- tips on getting apps featured, marketing tips, tips for first-time developers). Looking for your guidance on this one. 🙏

**Comment by daveverwer** [comment]
Apologies for the delayed reply, I've been away for a few days

Interesting question... I can't quite figure out if the AudioKit Pro is a paid thing (the Pro makes me think it is, but I can't find any details on pricing). I think if it's not, it doesn't matter much whether it goes in dev or company blogs, if there's a paid pro version I'd probably put it into company blogs.

I do see there's an AudioKit LLC at the bottom, so maybe company? Tough to know.

**Comment by analogcode** [comment]
Great question- It's 100% free & MIT open-source. The whole idea with the "Pro" is that it's powerful enough for professional iOS and audio developers. The LLC is so that we can publish the open-source examples to the app store under the name AudioKit. (The apps are also free)

**Comment by daveverwer** [comment]
Then I think I'm happy for it to be anywhere! Merged 🎉

**Comment by analogcode** [comment]
Thanks for the support! 🙏👍🏼

**Pull request merged**
