### PR TITLE
Update blogs.json(Added Shankar Madeshvaran Medium Blog)

### PR DESCRIPTION
**Pull request by shankarmadeshvaran**
Added Shankar Madeshvaran Medium Blog

### CODE REVIEW

**Comment by daveverwer** [comment]
Thanks! I think this would fit better in the "iOS Development Blogs" section rather than under "Platform and SDK Updates". Would you mind moving it there, please?

**Comment by shankarmadeshvaran** [comment]
Sure

**Comment by shankarmadeshvaran** [comment]
> Thanks! I think this would fit better in the "iOS Development Blogs" section rather than under "Platform and SDK Updates". Would you mind moving it there, please?

Please, go ahead

**Comment by daveverwer** [comment]
Sorry, clicked close by accident. I was suggesting you move it, just put it in the other section of the JSON.

**Comment by shankarmadeshvaran** [comment]
Moved My blog details to iOS Development Blogs Section. Please check once again and merge. Thanks

**Comment by daveverwer** [comment]
Thanks

**Pull request merged**
