### PR TITLE
Please, add Tiago Lopes' blog

### PR DESCRIPTION
**Pull request by TiagoMaiaL**
I'd like to add [my blog](https://tiagomaia.blog) to this directory. Thanks.

### CODE REVIEW

**Review by daveverwer — APPROVED** [review]
Thanks Tiago!

**Comment by daveverwer** [comment]
Looks like you're missing a comma at the end of the JSON dictionary. If you can add it, I'll merge!

**Comment by TiagoMaiaL** [comment]
I just fixed the comma, thanks.

**Comment by daveverwer** [comment]
Thanks!

**Pull request merged**
