### PR TITLE
[chore] Add a blog to Korean category blog section.

### PR DESCRIPTION
**Pull request by devKobe24**
- Add a blog name of "Evans Library"

Modified: blogs.json

### CODE REVIEW

**Comment by daveverwer** [comment]
Hi @devKobe24. Is this a Swift blog? I am relying entirely on Google Translate to check it, but I can't see any reference to Swift at all in the pages I checked. Could you give an example of some relevant content? It doesn't *all* have to be Swift-related, but just something.

Also, there is an additional unnecessary comma in the diff which is upsetting the validation.

Thanks!

**Comment by devKobe24** [comment]
HI @daveverwer, upon a detailed examination of this blog, it appears it is not solely a Swift blog. There are many other articles mixed in. Next time, I will ensure to understand the blog's precise intention before sending a PR.

**Comment by daveverwer** [comment]
It's fine if something is not ONLY a Swift blog, but I couldn't see any Swift at all there. If there is even a small amount then it qualifies.

**Comment by devKobe24** [comment]
Upon further review, it was found that the author of that blog is a JavaScript engineer and has not posted anything about Swift, hence it was removed. Additionally, Kobe's blog has been updated. Since all the Swift-related posts have disappeared from Kobe's blog, it has been removed as well for the time being

**Pull request closed without merging**
