### PR TITLE
added Spokestack to iOS Development Company

### PR DESCRIPTION
**Pull request by noelweichbrodt**

### CODE REVIEW

**Review by daveverwer — CHANGES_REQUESTED** [review]
Hi Noel, and thanks for your submission! It looks like there might be a couple of problems with the submission:

1. The URL you specify shows a 404 error. From a bit of investigation, I think this might be as simple as changing `tags` for `tag` as `https://www.spokestack.io/blog/tag/ios` looks like the correct URL.
2. The feed URL is wrong. Maybe a copy/paste error?

I'd be happy to accept the PR with these fixed. Ideally, the RSS feed would also be filtered to the iOS posts as the majority of the content on your blog looks to be Python and Android focused. Is that possible?

Thanks!

**Comment by daveverwer** [comment]
Thanks Noel!

**Comment by noelweichbrodt** [comment]
> I'd be happy to accept the PR with these fixed. 

Apologies, silly mistake on my part! Thanks for finding.

> Ideally, the RSS feed would also be filtered to the iOS posts as the majority of the content on your blog looks to be Python and Android focused. Is that possible?

I'm not able to figure out how to accomplish that at the moment, apologies!

**Comment by noelweichbrodt** [comment]
Thank you Dave!

**Pull request merged**
