### PR TITLE
Added the Swiftwater Series

### PR DESCRIPTION
**Pull request by ChrisMarshallNY**
Three series (two are finite, one is ongoing) on various aspects of the Swift Programming Language.

### CODE REVIEW

**Comment by daveverwer** [comment]
Hi Chris

I presume these are all tags on your blog? I actually can't find the blog the home page of your site, is there an index page somewhere?

I think rather than add three separate feeds, it might be appropriate just to add one that contains everything. Would that be appropriate in your opinion? The only thing I wanted to check was that these categories were not mixed in with a whole load of non-iOS content, but from the look of the other content on the site, I don't think that's going to be a problem.

Thanks!
Dave

**Comment by ChrisMarshallNY** [comment]
Hi Dave,

I hope that this finds you in good health, and good spirits.

It isn’t a blog site. It’s a corporate site, but my blogging section is “Miscellany.”

https://littlegreenviper.com/miscellany/

This includes general software development topics, as well as topics related to Swift/Apple development. I have a few series, and also a number of individual posts; several of which are reflected on Medium (https://medium.com/chrismarshallny).

I just submitted three series that I thought might be of interest.

The only ongoing one is Swiftwater. The other two are “finite” series. The Bluetooth one seemed to be fairly popular.

I use WordPress, so there are feeds. I don’t really have it set up in the default WordPress structure.

Yours Most Sincerely,

Chris Marshall

**Comment by daveverwer** [comment]
Hey Chris

I understand, thanks so much for the detailed explanation. I appreciate it.

I think your site would fit well with the site, but in the "Company Blogs" section and just with one entry with the "main" RSS feed that captures everything in the Miscellany section, is that possible?

Thanks
Dave

**Comment by ChrisMarshallNY** [comment]
I’ll see if that is possible. It probably should be, but it will need to wait until I get home.

Chris Marshall
Geek
Email: cmarshall@mac.com
Web Site: http://cmarshall.com

**Comment by ChrisMarshallNY** [comment]
Dave, I don't think that will work.

It's fine. Not that big a deal. The only thing that would qualify as a "blog," is the Swiftwater series. That's an ongoing series that I update when the mood hits me.

Otherwise, I have customized the site so much, that "Miscellany" isn't a semantically-addressable place.


Chris Marshall
ChrisMarshallNY <https://www.google.com/search?q=ChrisMarshallNY>
cmarshall@mac.com <mailto:cmarshall@mac.com>
chrismarshallny.com <https://chrismarshallny.com/>

**Comment by daveverwer** [comment]
Hey Chris. Thanks for that. Let's do this:

* Add your company blog with the RSS feed for the Swiftwater series in the company blogs section.
* Add your Medium to the personal blogs section. (I meant to say this along with my last reply, but forgot!)

**Comment by daveverwer** [comment]
Thanks Chris! Sorry it took so long to get this sorted out, thanks for your patience.

Dave

**Comment by ChrisMarshallNY** [comment]
No prob. Thanks for YOUR patience.

**Pull request merged**
